# fly.toml app configuration file generated for bible-reminder on 2023-06-29T16:37:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bible-reminder"
primary_region = "sin"
kill_signal = "SIGTERM"

#[deploy]
  # release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "bible-reminder.fly.dev"
  PORT = "8080"
  RELEASE_COOKIE = "qMbJvklAbHX3HH_EPwIex6ucf2pRvk7qmXecc5SfJizTM9ertY4vcA=="

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
