# fly.toml app configuration file generated for line-reminder-muddy-bird-4616-solitary-river-6269 on 2024-01-01T16:38:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "line-reminder-muddy-bird-4616-solitary-river-6269"
primary_region = "hkg"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "line-reminder-muddy-bird-4616-solitary-river-6269.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
